{7913}{7960}di non guardarlo nell'occhio...
{7961}{8032}perchè la sua|forza di concentrazione è tale che...
{8033}{8128}potrebbe provocare|un'emmoraggia cerebrale...
{8129}{8176}a quelli più deboli di voi.
{8177}{8224}Signor One, è pronto?|E ora, attenzione!
{8344}{8368}Piccolo ladruncolo!
{8369}{8464}Rubare i soldi degli orfani.|Ti insegno io!
{8465}{8488}Lasciali andare!
{8535}{8583}Cosa c'è?|Che succede?
{8584}{8631}Il poveretto non sta bene!
{13235}{13307}Non ti muovere!|Non ti muovere o ti disintegro!
{13690}{13738}Denree!
{13906}{13954}Uccidilo!
{14841}{14913}- Chi è quello?|- È I'uomo forzuto della fiera.
{14914}{14961}Non lo conosco
{14985}{15033}Cosa vuoi?
{15249}{15321}Ho perso il mio fratellino.
{15488}{15536}Non è venuto da solo.
{15920}{15992}Bravi, bravi, bambini, è stata dura?
{16016}{16088}Sembra che vi stiate|comportando molto bene.
{16089}{16136}Grazie per averci aspettato.
{16184}{16232}Grazie.
{16519}{16591}Ricordati,|le mie orecchie sono così affilate...
{16592}{16663}che possono sentire quello che pensate.
{16927}{16975}Andate a comprarvi i dolcetti.
{17095}{17143}Non esagerare.
{17144}{17191}Avanti. Alza il culo.
{17287}{17311}Avanti.|Eccomi.
{17335}{17383}Muoviti!
{17502}{17550}Prendiamo gli strumenti e battiamocela.
{17574}{17646}Muovetevi!
{17647}{17694}Quelgli schifosi Ciclopi.
{17695}{17766}Non preoccuparti.|Sappiamo dove trovarli.
