{40}{160}Downloaded From www.AllSubs.org
{3980}{4052}Il mio povero bambino.
{4843}{4915}Chi ha rubato i sogni dei bambini?
{4916}{5011}Quel pazzo genio di Krank|col suo piano diabolico.
{5012}{5107}A quali viziose profondità|non arriverà?
{5108}{5155}Il racconto si trasformerà in tragedia...
{5156}{5203}o avrà un finale felice?
{6521}{6569}Salite, signore e signori!
{6570}{6617}Salite! Venite più vicino.
{6618}{6665}Non abbiate paura.
{6666}{6713}Venite a vedere I'uomo più forte del mondo.
{6714}{6785}Guardate quelle catene,|fatte dello stesso d'acciaio...
{6786}{6857}di quello usato per alzare...
{6858}{6905}si, amici miei...
{6906}{6953}La vera luce è invisibile.
{6954}{7001}Attraversate il corridoio delle ombre...
{7002}{7097}ed entrerete|nel mondo dei prescelti.
{7098}{7145}Rinunciate al dono della vista.
{7146}{7217}So che ci sono degli scettici fra voi...
{7218}{7289}timorosi di condividere con noi|i morti della notte.
{7290}{7361}Siate coraggiosi.|Rinunciate al dono della vista.
{7362}{7433}Spalancate i vostri occhi.|Venite con noi.
{7434}{7504}Aiutateci a costruire un mondo migliore.
{7505}{7600}ll trita ossa proverà ancora|a spezzare I'acciaio...
{7601}{7720}usando solo la forza|delle sue possenti braccia.
{7721}{7792}Per favore, signore e signori,|desidero silenzio assoluto...
{7793}{7840}durante la dimostrazione.
{7841}{7912}Devo chiedervi,|per la vostra sicurezza...
{7913}{7960}di non guardarlo nell'occhio...
{7961}{8032}perchè la sua|forza di concentrazione è tale che...
{8033}{8128}potrebbe provocare|un'emmoraggia cerebrale...
{8129}{8176}a quelli più deboli di voi.
{8177}{8224}Signor One, è pronto?|E ora, attenzione!
{8344}{8368}Piccolo ladruncolo!
{8369}{8464}Rubare i soldi degli orfani.|Ti insegno io!
{8465}{8488}Lasciali andare!
{8535}{8583}Cosa c'è?|Che succede?
{8584}{8631}Il poveretto non sta bene!
{13235}{13307}Non ti muovere!|Non ti muovere o ti disintegro!
{13690}{13738}Denree!
{13906}{13954}Uccidilo!
{14841}{14913}- Chi è quello?|- È I'uomo forzuto della fiera.
{14914}{14961}Non lo conosco
{14985}{15033}Cosa vuoi?
{15249}{15321}Ho perso il mio fratellino.
{15488}{15536}Non è venuto da solo.
{15920}{15992}Bravi, bravi, bambini, è stata dura?
{16016}{16088}Sembra che vi stiate|comportando molto bene.
{16089}{16136}Grazie per averci aspettato.
{16184}{16232}Grazie.
{16519}{16591}Ricordati,|le mie orecchie sono così affilate...
{16592}{16663}che possono sentire quello che pensate.
{16927}{16975}Andate a comprarvi i dolcetti.
{17095}{17143}Non esagerare.
{17144}{17191}Avanti. Alza il culo.
{17287}{17311}Avanti.|Eccomi.
{17335}{17383}Muoviti!
{17502}{17550}Prendiamo gli strumenti e battiamocela.
{17574}{17646}Muovetevi!
{17647}{17694}Quelgli schifosi Ciclopi.
{17695}{17766}Non preoccuparti.|Sappiamo dove trovarli.
{
